name: test dynamic index functionality
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup minio
        uses: infleet/minio-action@v0.0.1
        with:
          port: "9000"
          version: "latest"
          username: "minio"
          password: "minio"
          bucket : "backups"
