name: test dynamic index functionality
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup MinIO Server
        uses: infleet/minio-action@v0.0.1
        with:
          port: "9000"
          version: "latest"
      - name: Setup MinIO client
        uses: yakubique/setup-minio-cli@v1
      - name: Setup golang
        uses: actions/setup-go@v5
      - name: "Create minio access"
        run: |
          mc alias set 'ci' 'http://127.0.0.1:9000' 'minioadmin' 'minioadmin'
          mc mb ci/backups
          mc admin user svcacct add ci minioadmin --json > /tmp/minio.json
      - name: "Install proxmox backup client"
        run: |
          sudo apt update -y >/dev/null 2>&1
          sudo apt install jq wget -y >/dev/null 2>&1
          sudo wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
          echo "deb http://download.proxmox.com/debian/pbs-client bullseye main" | sudo tee -a /etc/apt/sources.list.d/pbs.list
          sudo apt update -y >/dev/null 2>&1
          sudo apt install -y proxmox-backup-client
      - name: "Create backup"
        run: |
          go run tizbac/pmoxs3backuproxy/cmd/pmoxs3backuproxy -endpoint 127.0.0.1:9000 -bind 127.0.0.1:8007  -debug &
          export PBS_PASSWORD=$(jq -r .secretKey < /tmp/minio.json)
          export USERNAME=$(jq -r .accessKey < /tmp/minio.json)
          sudo -E proxmox-backup-client backup root.pxar:/etc --repository "$USERNAME@pbs@127.0.0.1:backups"
